# access the hexo editor directly
local: false

# the username to login hexo editor
username: hexo

# the password for logining hexo editor
password: imyouradmin

# the blog directory
base_dir: /home/tajpure/workspace/tajpure

# port
port: 2048

# redis host
redis_host: 127.0.0.1

# redis port
redis_port: 6379
