# access the hexo editor directly
local: true
# the username to logining hexo editor
username: admin
# the password for logining hexo editor
password: admin
# the blog directory
base_dir: /home/tajpure/workspace/blog0
